### PR TITLE
Added PHP 7.3 support - updated Travis CI configuration

### PR DESCRIPTION
**Pull request by webimpress**

### CODE REVIEW

**Comment by webimpress** [comment]
@weierophinney Changed target to `master` and rebased.

**Comment by weierophinney** [comment]
Just noticed this removes support for zend-stdlib v2 releases, so I'll target 2.9.0 after all - sorry for the busy-work, @webimpress !

**Comment by webimpress** [comment]
@weierophinney ok: changed target to develop

**Comment by weierophinney** [comment]
Thanks, @webimpress!

**Pull request merged**
