### PR TITLE
Fix for timeout config parameter validation

### PR DESCRIPTION
**Pull request by klimser**
Validation conditions for integer or numeric timeout was mutually exclusive, fixed.

### CODE REVIEW

**Comment by klimser** [comment]
@webimpress There are already existed tests that were failed and now passed: 
- test/Client/CurlTest/testPassValidTimeout
- test/Client/SocketTest/testPassValidTimeout

**Comment by webimpress** [comment]
@klimser 

> There are already existed tests that were failed ...

3 days ago builds on `master` and `develop` pass and nothing has been changed since then. How do you mean that these test were failing? Where?

**Comment by klimser** [comment]
> 
> 
> @klimser
> 
> > There are already existed tests that were failed ...
> 
> 3 days ago builds on `master` and `develop` pass and nothing has been changed since then. How do you mean that these test were failing? Where?

I've updated my project to current release -> project was destroyed -> I found the reason, place in code ->I found that changes were made with tests -> I ran tests -> I got exception -> I fixed a bug -> Tests passed -> I created a pull request.

**Comment by klimser** [comment]
@webimpress 

> @klimser
> 
> > There are already existed tests that were failed ...
> 
> 3 days ago builds on `master` and `develop` pass and nothing has been changed since then. How do you mean that these test were failing? Where?

These tests are the only when `TESTS_ZEND_HTTP_CLIENT_BASEURI` set to true and skipped otherwise, maybe it's the reason?

**Comment by samsonasik** [comment]
actually, the `! is_int($connectTimeout)` is not needed as the `! is_numeric()` already cover it, and later will always be casted to `(int) $connectTimeout` in next line.

**Comment by klimser** [comment]
> 
> 
> actually, the `! is_int($connectTimeout)` is not needed as the `! is_numeric()` already cover it, and later will always be casted to `(int) $connectTimeout` in next line.

Agree. Fixed.

**Comment by weierophinney** [comment]
Thanks, @klimser.

**Pull request merged**
