### PR TITLE
Fix #21

### LINKED ISSUE #21: Zend/Http/Header/AbstractAccept throws php notice when "HTTP_ACCEPT_LANGUAGE" is non well formatted
Hi,

An error occured when we try to retrieve "Accept-Language" from request headers and "$_SERVER['HTTP_ACCEPT_LANGUAGE']" is non well formatted : ""Undefined offset: 1" - /.../Zend/Http/Header/AbstractAccept.php (173)"

The following unit test shows this behavior.

```php
    public function testDefineDefaultLocaleWithWrongHttpAcceptLanguageHeader()
    {
        $_SERVER['HTTP_ACCEPT_LANGUAGE'] = 'en-US;en';
        $oRequest = new \Zend\Http\PhpEnvironment\Request();
        $oRequest->getHeaders()->get('Accept-Language'); // Php notice
    }
```
Thanks for helping me to fix it

### PR DESCRIPTION
**Pull request by neilime**
Prevents non well formatted accept  header value.

Fix #21

### CODE REVIEW

**Comment by Freeaqingme** [comment]
Awesome!

As you can see above one of the CS checks failed, apparently on some trailing spaces. Something you could perhaps take a look at as well?

Results are here: https://travis-ci.org/zendframework/zend-http/jobs/83107792

**Comment by neilime** [comment]
Done !

**Comment by Freeaqingme** [comment]
@Maks3w Is this something you could look at? I've been out of the game for quite some time (although I still feel for this particular component), so am I little uncomfortable merging it. As far as I'm concerned it's ready to go!

**Comment by Maks3w** [comment]
Well I have questions. 

1. Because an abstract class has been modified then any child test should have a test and not only Abstract-Language

2. After take a look to http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html I don't see those headers should share the same ABNF so I think the abstract class should be split with trait functions and be deprecated

**Comment by Maks3w** [comment]
Errata: RFC2616 are expressed using [EBNF](https://tools.ietf.org/html/rfc822)

Accept-Header is defined individually on [RFC3282](https://tools.ietf.org/html/rfc3282)

**Comment by Maks3w** [comment]
After reading RFC 7231 only the weight param (`;q=[0,0.001-1]`) is common to all those headers but the rest of parsing values are not.

This is the resume of ABNF rules from http://tools.ietf.org/html/rfc7231#appendix-D
```
Accept = [ ( "," / ( media-range [ accept-params ] ) ) *( OWS "," [OWS ( media-range [ accept-params ] ) ] ) ]
Accept-Charset = *( "," OWS ) ( ( charset / "*" ) [ weight ] ) *( OWS "," [ OWS ( ( charset / "*" ) [ weight ] ) ] )
Accept-Encoding = [ ( "," / ( codings [ weight ] ) ) *( OWS "," [ OWS ( codings [ weight ] ) ] ) ]
Accept-Language = *( "," OWS ) ( language-range [ weight ] ) *( OWS "," [ OWS ( language-range [ weight ] ) ] )

accept-params = weight *accept-ext
weight = OWS ";" OWS "q=" qvalue

OWS = Optional White Space
```

**Comment by Freeaqingme** [comment]
@Maks3w How is this all relevant for this particular pull request? Fwiw, the implementations that are included in zend\http for the various accept header types come with own regexes to support and validate the different formats.

Of course we can always refactor this class and deprecate parts of it. But that seems way beyond the scope of this particular issue: Ensuring no notices are thrown on invalid input.

**Comment by Maks3w** [comment]
Reading the RFC and the ABNF resume split languages with `;` is not allowed. Should be `,`. So the proposed solution is wrong. The header was malformed and there is nothing to fix.

**Comment by Maks3w** [comment]
Closed due inactivity.

**Pull request closed without merging**
