### PR TITLE
FIX - Put back the insensitive replacements for Transfer-Encoding and Content-Encoding.

### PR DESCRIPTION
**Pull request by nbochenko**

### CODE REVIEW

**Comment by nbochenko** [comment]
@blanchonvincent

**Comment by Martin-P** [comment]
@nbochenko Perhaps you can add some text to this PR and:
- explain what bug you encountered
- create unit tests to reproduce the issue
- explain why your code change is a fix for your issue

**Comment by weierophinney** [comment]
@nbochenko Ping - Please see the comments from @Martin-P ; we need more detail, specifically in the form of unit tests, to ensure that the changes are correct, and that we don't accidentally revert them in the future.

**Comment by Maks3w** [comment]
Closed due inactivity

**Comment by wiese** [comment]
I get your point wanting a test for this, so we don't break it again in the future, but this fixes a real bug introduced during https://github.com/nbochenko/zend-http/commit/ddf5a83c60120450cc15467a886192de4f2c229f, which noboby had any issue merging into the main line without a test - so some initiative from the core team and the original author should be just as expected as from someone who, at least, found the bug and was kind enough to report it. I'll try and contribute some coverage here rather sooner than later.

**Comment by Martin-P** [comment]
Ping @Maks3w  @weierophinney.
I can confirm what @wiese says. @kasitmp never added any tests to the original PR (https://github.com/zendframework/zf2/pull/6691) and @weierophinney just merged the PR without tests.

Before https://github.com/zendframework/zf2/pull/6691 there was `stri_replace` (watch the **i**), but that PR removed the case-insensitive matching and made it case-sensitive.

Perhaps @kasitmp or @weierophinney can add the proper tests for this as they caused this issue :wink:

**Pull request closed without merging**
