### PR TITLE
All headers are case insensitive and should be treated as such to pre…

### PR DESCRIPTION
**Pull request by lucian303**
…vent errors. See: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

Fixes https://github.com/zendframework/zf2/issues/7683

### CODE REVIEW

**Comment by Ocramius** [comment]
Missing tests

**Comment by lucian303** [comment]
I wouldn't even know how to go about writing tests for this even if I had the time to. I guess until someone does, the Curl adapter will stay broken.

**Comment by ezimuel** [comment]
@lucian303 I sent a PR against your repository with the unit tests.

**Comment by ezimuel** [comment]
@lucian303 please merge https://github.com/lucian303/zend-http/pull/1 that adds the unit test for your PR.

**Comment by ezimuel** [comment]
@lucian303 I'm sorry but I sent the PR against your `master` branch instead of the right one :( I re-sent the PR [here](https://github.com/lucian303/zend-http/pull/2), please merge again.

**Comment by lucian303** [comment]
Yup, no problem.

**Comment by ezimuel** [comment]
Fixed CS issues during the merge in master/develop. Thanks to @lucian303 for the contribution!

**Pull request closed without merging**
